{"mode":"dev","input_data":"Exception in thread \"main\" java.lang.NullPointerException\n        at com.example.myproject.Book.getTitle(Book.java:16)\n        at com.example.myproject.Author.getBookTitles(Author.java:25)\n        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)\njava.lang.NullPointerException\n  at com.temp.ttscancel.MainActivity.onCreate(MainActivity.java:43)\n  at android.app.Activity.performCreate(Activity.java:5248)\n  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)\n  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)\n  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)\n  at android.app.ActivityThread.access$800(ActivityThread.java:139)\n  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)\n  at android.os.Handler.dispatchMessage(Handler.java:102)\n  at android.os.Looper.loop(Looper.java:136)\n  at android.app.ActivityThread.main(ActivityThread.java:5097)\n  at java.lang.reflect.Method.invokeNative(Native Method)\n  at java.lang.reflect.Method.invoke(Method.java:515)\n  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)\n  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)\nException in thread \"main\" java.lang.RuntimeException: A test exception\n  at com.stackify.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)\n  at com.stackify.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)\n  at com.stackify.stacktrace.StackTraceExample.main(StackTraceExample.java:5)\nException in thread \"main\" java.lang.NullPointerException\n        at com.example.myproject.Book.getTitle(Book.java:16)\n        at com.example.myproject.Author.getBookTitles(Author.java:25)\n        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)\n","tdd":"Dec 23 12:11:43 louis postfix/smtpd[31499]: connect from unknown[95.75.93.154]\nDec 23 14:42:56 louis named[16000]: client 199.48.164.7#64817: query (cache) 'amsterdamboothuren.com/MX/IN' denied\nDec 23 14:30:01 louis CRON[619]: (www-data) CMD (php /usr/share/cacti/site/poller.php >/dev/null 2>/var/log/cacti/poller-error.log)\nDec 22 18:28:06 louis rsyslogd: [origin software=\"rsyslogd\" swVersion=\"4.2.0\" x-pid=\"2253\" x-info=\"http://www.rsyslog.com\"] rsyslogd was HUPed, type 'lightweight'.\nFeb 23 11:23:46 louis systemd-resolved[1285]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.\nFeb 23 11:32:10 louis tilix[26495]: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)\nFeb 23 11:32:06 louis kernel: [60390.791792] kauditd_printk_skb: 470 callbacks suppressed\nFeb 23 11:17:01 louis CRON[1853]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)\nFeb 22 13:50:40 louis snapd[1727]: udevmon.go:190: udev monitor observed remove event for unknown device \"/sys/mm_struct(7838:phpsessionclean.service)\"","logstash_filter":"filter {\n\n}","input_fields":[{"attribute":"type","value":"java-stack-trace"}],"custom_logstash_patterns":"","custom_codec":"multiline {\n  pattern => \"^\\s\"\n  what => \"previous\"\n}","filter_regex_enabled":false,"filter_reverse_match_enabled":false,"filter_display":"","number_lines_display":"10"}